[libdefaults]
  default_realm = EXAMPLE.TEST
  dns_lookup_realm = false
  dns_lookup_kdc = false
  rdns = false
  udp_preference_limit = 1

[realms]
  EXAMPLE.TEST = {
    kdc = kdc.example.test
    admin_server = kdc.example.test
  }

[domain_realm]
  .example.test = EXAMPLE.TEST
  example.test = EXAMPLE.TEST
